<a href="https://colab.research.google.com/github/LuisPalominoR/Entregable-1-Primera-Parte/blob/main/Entregable_1_b_PROTO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [152]:
%load_ext rpy2.ipython

The rpy2.ipython extension is already loaded. To reload it, use:
  %reload_ext rpy2.ipython


**Vectores**

Creación de data

In [153]:
import numpy as np

SurnamesP=np.array(["Milei", "Arce", "da Silva", "Boric", "Petro", "Chaves", "Díaz-Canel",
           "Noboa", "Bukele", "Arévalo", "Castro", "López Obrador",
           "Ortega", "Cortizo", "Peña", "Boluarte", "Abinader", "Lacalle Pou", "Maduro"])
agesP=np.array([53,60,78,37,63,62,63,36,42,65,64,70,78,70,45,61,56,50,61])
countriesP=np.array(["Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica", "Cuba",
            "Ecuador", "El Salvador", "Guatemala", "Honduras", "México", "Nicaragua", "Panamá",
            "Paraguay", "Perú", "República Dominicana", "Uruguay", "Venezuela"])
pol_orientationP=np.array(["Derecha", "Izquierda", "Izquierda", "Centroizquierda", "Izquierda", "Centroderecha",
                  "Izquierda", "Centroderecha", "Centro", "Izquierda", "Centroizquierda", "Izquierda",
                  "Izquierda", "Centro", "Centroderecha", "Centro", "Centroizquierda", "Centroderecha",
                  "Izquierda"])

In [154]:
SurnamesP

array(['Milei', 'Arce', 'da Silva', 'Boric', 'Petro', 'Chaves',
       'Díaz-Canel', 'Noboa', 'Bukele', 'Arévalo', 'Castro',
       'López Obrador', 'Ortega', 'Cortizo', 'Peña', 'Boluarte',
       'Abinader', 'Lacalle Pou', 'Maduro'], dtype='<U13')

In [155]:
%%R
SurnamesR=c("Milei", "Arce", "da Silva", "Boric", "Petro", "Chaves", "Díaz-Canel",
           "Noboa", "Bukele", "Arévalo", "Castro", "López Obrador",
           "Ortega", "Cortizo", "Peña", "Boluarte", "Abinader", "Lacalle Pou", "Maduro")
agesR=c(53,60,78,37,63,62,63,36,42,65,64,70,78,70,45,61,56,50,61)
countriesR=c("Argentina", "Bolivia", "Brasil", "Chile", "Colombia", "Costa Rica", "Cuba",
            "Ecuador", "El Salvador", "Guatemala", "Honduras", "México", "Nicaragua", "Panamá",
            "Paraguay", "Perú", "República Dominicana", "Uruguay", "Venezuela")
pol_orientationR=c("Derecha", "Izquierda", "Izquierda", "Centroizquierda", "Izquierda", "Centroderecha",
                  "Izquierda", "Centroderecha", "Centro", "Izquierda", "Centroizquierda", "Izquierda",
                  "Izquierda", "Centro", "Centroderecha", "Centro", "Centroizquierda", "Centroderecha",
                  "Izquierda")

In [156]:
%%R
SurnamesR

 [1] "Milei"         "Arce"          "da Silva"      "Boric"        
 [5] "Petro"         "Chaves"        "Díaz-Canel"    "Noboa"        
 [9] "Bukele"        "Arévalo"       "Castro"        "López Obrador"
[13] "Ortega"        "Cortizo"       "Peña"          "Boluarte"     
[17] "Abinader"      "Lacalle Pou"   "Maduro"       


Acceso a la data

In [157]:
agesP[0]

53

La primera edad obtenida es 53.

In [158]:
%%R
agesR[2]

[1] 60


La segunda edad obtenida es 60.

In [159]:
#Último elemento
countriesP[-2]

'Uruguay'

El penúltimo país es Uruguay.

In [160]:
%%R
tail(countriesR,1)

[1] "Venezuela"


El último país es Venezuela.

Cortes

In [161]:
agesP[1:4]

array([60, 78, 37])

Se obtiene de la segunda a la cuarta edad.

In [162]:
%%R
agesR[3:5]

[1] 78 37 63


Se obtiene de la tercera a la quinta edad.

In [163]:
#De forma no consecutiva
agesP[[0,2,3]]

array([53, 78, 37])

Se obtiene la primera, la tercera y la cuarta edad.

In [164]:
%%R
agesR[c(5,7,9)]

[1] 63 63 42


Se obtiene la quinta, la séptima y la novena edad.

Reemplazo por Posición

In [165]:
countriesP[1]="EP Bolivia"
countriesP

array(['Argentina', 'EP Bolivia', 'Brasil', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Ecuador', 'El Salvador', 'Guatemala',
       'Honduras', 'México', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú',
       'República Dominicana', 'Uruguay', 'Venezuela'], dtype='<U20')

Se reemplazó Bolivia por EP Bolivia (Estado Plurinacional de Bolivia).

In [166]:
%%R
countriesR[19]="RP Venezuela"
countriesR

 [1] "Argentina"            "Bolivia"              "Brasil"              
 [4] "Chile"                "Colombia"             "Costa Rica"          
 [7] "Cuba"                 "Ecuador"              "El Salvador"         
[10] "Guatemala"            "Honduras"             "México"              
[13] "Nicaragua"            "Panamá"               "Paraguay"            
[16] "Perú"                 "República Dominicana" "Uruguay"             
[19] "RP Venezuela"        


Se reemplazó Venezuela por RP Venezuela (República Bolivariana de Venezuela).

Reemplazo por Valor

In [167]:
countriesP=np.char.replace(countriesP, 'Brasil', 'Brazil')
countriesP

array(['Argentina', 'EP Bolivia', 'Brazil', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Ecuador', 'El Salvador', 'Guatemala',
       'Honduras', 'México', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú',
       'República Dominicana', 'Uruguay', 'Venezuela'], dtype='<U20')

Se reemplazó Brasil por Brazil.

In [168]:
%%R
countriesR[countriesR=='México']="Estados Unidos Mexicanos"
countriesR

 [1] "Argentina"                "Bolivia"                 
 [3] "Brasil"                   "Chile"                   
 [5] "Colombia"                 "Costa Rica"              
 [7] "Cuba"                     "Ecuador"                 
 [9] "El Salvador"              "Guatemala"               
[11] "Honduras"                 "Estados Unidos Mexicanos"
[13] "Nicaragua"                "Panamá"                  
[15] "Paraguay"                 "Perú"                    
[17] "República Dominicana"     "Uruguay"                 
[19] "RP Venezuela"            


Se reemplazó México por Estados Unidos Mexicanos.

Eliminación por Posición

In [169]:
countriesP=np.delete(countriesP,-3)
countriesP

array(['Argentina', 'EP Bolivia', 'Brazil', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Ecuador', 'El Salvador', 'Guatemala',
       'Honduras', 'México', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú',
       'Uruguay', 'Venezuela'], dtype='<U20')

Se eliminó el antepenúltimo país, República Dominicana.

In [170]:
%%R
countriesR=countriesR[-length(countriesR)]
countriesR

 [1] "Argentina"                "Bolivia"                 
 [3] "Brasil"                   "Chile"                   
 [5] "Colombia"                 "Costa Rica"              
 [7] "Cuba"                     "Ecuador"                 
 [9] "El Salvador"              "Guatemala"               
[11] "Honduras"                 "Estados Unidos Mexicanos"
[13] "Nicaragua"                "Panamá"                  
[15] "Paraguay"                 "Perú"                    
[17] "República Dominicana"     "Uruguay"                 


Se eliminó el último país, Venezuela.

In [171]:
#Para varias posiciones
pol_orientationP=np.delete(pol_orientationP,range(1,4))
pol_orientationP

array(['Derecha', 'Izquierda', 'Centroderecha', 'Izquierda',
       'Centroderecha', 'Centro', 'Izquierda', 'Centroizquierda',
       'Izquierda', 'Izquierda', 'Centro', 'Centroderecha', 'Centro',
       'Centroizquierda', 'Centroderecha', 'Izquierda'], dtype='<U15')

Se eliminaron el segundo, tercer y cuarto valor del vector de Orientación Política.

In [172]:
%%R
pol_orientationR=pol_orientationR[-c(3:5)]
pol_orientationR

 [1] "Derecha"         "Izquierda"       "Centroderecha"   "Izquierda"      
 [5] "Centroderecha"   "Centro"          "Izquierda"       "Centroizquierda"
 [9] "Izquierda"       "Izquierda"       "Centro"          "Centroderecha"  
[13] "Centro"          "Centroizquierda" "Centroderecha"   "Izquierda"      


Se eliminaron el tercer, cuarto y quinto valor del vector de Orientación Política.

In [173]:
# De forma no consecutiva
byeIndex=[1, 3, 5]
agesP_new=np.delete(agesP,byeIndex)
agesP_new

array([53, 78, 63, 63, 36, 42, 65, 64, 70, 78, 70, 45, 61, 56, 50, 61])

Se eliminaron la segunda, cuarta y sexta edad.

In [174]:
%%R
agesR_new=agesR[-c(3,5,7)]
agesR_new

 [1] 53 60 37 62 36 42 65 64 70 78 70 45 61 56 50 61


Se eliminaron la tercera, quinta y séptima edad.

Eliminación por Valor

In [175]:
agesP_new2=np.delete(agesP_new, np.where(agesP_new == 56))
agesP_new2

array([53, 78, 63, 63, 36, 42, 65, 64, 70, 78, 70, 45, 61, 50, 61])

Se eliminó la edad 56 del vector.

In [176]:
%%R
agesR_new2=agesR_new[agesR_new!=45]
agesR_new2

 [1] 53 60 37 62 36 42 65 64 70 78 70 61 56 50 61


Se eliminó la edad 45 del vector.

In [177]:
agesP_new3=np.delete(agesP_new2, np.isin(agesP_new2,[50,70]))
agesP_new3

array([53, 78, 63, 63, 36, 42, 65, 64, 78, 45, 61, 61])

Se eliminaron las edades 50 y 70 del vector.

In [178]:
%%R
agesR_new3=agesR_new2[!agesR_new2%in%c(60,65)]
agesR_new3

 [1] 53 37 62 36 42 64 70 78 70 61 56 50 61


Se eliminaron las edades 60 y 65 del vector.

Inserción de valores al final del vector

In [179]:
countriesP_new=np.array(["España","Portugal","Estados Unidos"])
countriesP_new2=np.append(countriesP,countriesP_new)
countriesP_new2

array(['Argentina', 'EP Bolivia', 'Brazil', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Ecuador', 'El Salvador', 'Guatemala',
       'Honduras', 'México', 'Nicaragua', 'Panamá', 'Paraguay', 'Perú',
       'Uruguay', 'Venezuela', 'España', 'Portugal', 'Estados Unidos'],
      dtype='<U20')

Se añadieron España, Portugal y Estados Unidos al vector.

In [180]:
%%R
countriesR_new=c("Canadá","Italia","Francia")
countriesR_new2=c(countriesR,countriesR_new)
countriesR_new2

 [1] "Argentina"                "Bolivia"                 
 [3] "Brasil"                   "Chile"                   
 [5] "Colombia"                 "Costa Rica"              
 [7] "Cuba"                     "Ecuador"                 
 [9] "El Salvador"              "Guatemala"               
[11] "Honduras"                 "Estados Unidos Mexicanos"
[13] "Nicaragua"                "Panamá"                  
[15] "Paraguay"                 "Perú"                    
[17] "República Dominicana"     "Uruguay"                 
[19] "Canadá"                   "Italia"                  
[21] "Francia"                 


Se añadieron Canadá, Italia y Francia al vector.

Inserción de valores en una posición específica

In [181]:
countriesP_new3=np.insert(countriesP_new2,obj=11,values="Inglaterra")
countriesP_new3

array(['Argentina', 'EP Bolivia', 'Brazil', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Ecuador', 'El Salvador', 'Guatemala',
       'Honduras', 'Inglaterra', 'México', 'Nicaragua', 'Panamá',
       'Paraguay', 'Perú', 'Uruguay', 'Venezuela', 'España', 'Portugal',
       'Estados Unidos'], dtype='<U20')

Inglaterra fue añadido como el undécimo elemento del vector.

In [182]:
%%R
countriesR_new3=append(countriesR_new2,"Alemania",after=1)
countriesR_new3

 [1] "Argentina"                "Alemania"                
 [3] "Bolivia"                  "Brasil"                  
 [5] "Chile"                    "Colombia"                
 [7] "Costa Rica"               "Cuba"                    
 [9] "Ecuador"                  "El Salvador"             
[11] "Guatemala"                "Honduras"                
[13] "Estados Unidos Mexicanos" "Nicaragua"               
[15] "Panamá"                   "Paraguay"                
[17] "Perú"                     "República Dominicana"    
[19] "Uruguay"                  "Canadá"                  
[21] "Italia"                   "Francia"                 


Alemania fue añadido como el segundo elemento del vector.

Concatenación

In [183]:
vector_new=np.concatenate((countriesP_new3,pol_orientationP))
vector_new

array(['Argentina', 'EP Bolivia', 'Brazil', 'Chile', 'Colombia',
       'Costa Rica', 'Cuba', 'Ecuador', 'El Salvador', 'Guatemala',
       'Honduras', 'Inglaterra', 'México', 'Nicaragua', 'Panamá',
       'Paraguay', 'Perú', 'Uruguay', 'Venezuela', 'España', 'Portugal',
       'Estados Unidos', 'Derecha', 'Izquierda', 'Centroderecha',
       'Izquierda', 'Centroderecha', 'Centro', 'Izquierda',
       'Centroizquierda', 'Izquierda', 'Izquierda', 'Centro',
       'Centroderecha', 'Centro', 'Centroizquierda', 'Centroderecha',
       'Izquierda'], dtype='<U20')

Se concatenaron los vectores de países y orientaciones políticas.

In [184]:
%%R
vector_newR=c(countriesR_new3,pol_orientationR)
vector_newR

 [1] "Argentina"                "Alemania"                
 [3] "Bolivia"                  "Brasil"                  
 [5] "Chile"                    "Colombia"                
 [7] "Costa Rica"               "Cuba"                    
 [9] "Ecuador"                  "El Salvador"             
[11] "Guatemala"                "Honduras"                
[13] "Estados Unidos Mexicanos" "Nicaragua"               
[15] "Panamá"                   "Paraguay"                
[17] "Perú"                     "República Dominicana"    
[19] "Uruguay"                  "Canadá"                  
[21] "Italia"                   "Francia"                 
[23] "Derecha"                  "Izquierda"               
[25] "Centroderecha"            "Izquierda"               
[27] "Centroderecha"            "Centro"                  
[29] "Izquierda"                "Centroizquierda"         
[31] "Izquierda"                "Izquierda"               
[33] "Centro"                   "Centroderecha"         

Se concatenaron los vectores de países y orientaciones políticas.